import { z } from 'zod';
export declare const createServiceSchema: z.ZodObject<{
    appointmentId: z.ZodOptional<z.ZodNumber>;
    clientId: z.ZodNumber;
    vehicleId: z.ZodNumber;
    mechanicId: z.ZodOptional<z.ZodNumber>;
    statusId: z.ZodDefault<z.ZodNumber>;
    problemDescription: z.ZodOptional<z.ZodString>;
    diagnosis: z.ZodOptional<z.ZodString>;
    quotationDetails: z.ZodOptional<z.ZodString>;
    laborPrice: z.ZodDefault<z.ZodNumber>;
    partsPrice: z.ZodDefault<z.ZodNumber>;
    partsCost: z.ZodDefault<z.ZodNumber>;
    totalAmount: z.ZodDefault<z.ZodNumber>;
    truput: z.ZodDefault<z.ZodNumber>;
    mechanicCommission: z.ZodDefault<z.ZodNumber>;
}, z.core.$strip>;
export declare const vehicleReceptionSchema: z.ZodObject<{
    appointmentId: z.ZodOptional<z.ZodNumber>;
    clientId: z.ZodNumber;
    vehicleId: z.ZodNumber;
    kilometraje: z.ZodNumber;
    nivelCombustible: z.ZodEnum<{
        "1/4": "1/4";
        "1/2": "1/2";
        "3/4": "3/4";
        FULL: "FULL";
    }>;
    lucesOk: z.ZodDefault<z.ZodBoolean>;
    llantasOk: z.ZodDefault<z.ZodBoolean>;
    cristalesOk: z.ZodDefault<z.ZodBoolean>;
    carroceriaOk: z.ZodDefault<z.ZodBoolean>;
    observacionesRecepcion: z.ZodOptional<z.ZodString>;
    firmaCliente: z.ZodString;
    fotosRecepcion: z.ZodOptional<z.ZodArray<z.ZodString>>;
}, z.core.$strip>;
export declare const updateServiceSchema: z.ZodObject<{
    appointmentId: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    clientId: z.ZodOptional<z.ZodNumber>;
    vehicleId: z.ZodOptional<z.ZodNumber>;
    mechanicId: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    statusId: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    problemDescription: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    diagnosis: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    quotationDetails: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    laborPrice: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    partsPrice: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    partsCost: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    totalAmount: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    truput: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    mechanicCommission: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    id: z.ZodNumber;
    startedAt: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
    completedAt: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
}, z.core.$strip>;
export declare const serviceStatusUpdateSchema: z.ZodObject<{
    id: z.ZodNumber;
    newStatusId: z.ZodNumber;
    notes: z.ZodOptional<z.ZodString>;
}, z.core.$strip>;
export declare const serviceFilterSchema: z.ZodObject<{
    page: z.ZodPipe<z.ZodOptional<z.ZodString>, z.ZodTransform<number, string | undefined>>;
    limit: z.ZodPipe<z.ZodOptional<z.ZodString>, z.ZodTransform<number, string | undefined>>;
    sortBy: z.ZodOptional<z.ZodString>;
    sortOrder: z.ZodPipe<z.ZodOptional<z.ZodString>, z.ZodTransform<"asc" | "desc", string | undefined>>;
    search: z.ZodOptional<z.ZodString>;
    clientId: z.ZodOptional<z.ZodCoercedNumber<unknown>>;
    vehicleId: z.ZodOptional<z.ZodCoercedNumber<unknown>>;
    mechanicId: z.ZodOptional<z.ZodCoercedNumber<unknown>>;
    statusId: z.ZodOptional<z.ZodCoercedNumber<unknown>>;
    dateFrom: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
    dateTo: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodDate]>>;
}, z.core.$strip>;
export type CreateServiceInput = z.infer<typeof createServiceSchema>;
export type UpdateServiceInput = z.infer<typeof updateServiceSchema>;
export type ServiceStatusUpdateInput = z.infer<typeof serviceStatusUpdateSchema>;
export type ServiceFilterInput = z.infer<typeof serviceFilterSchema>;
export type VehicleReceptionInput = z.infer<typeof vehicleReceptionSchema>;
